# Generated by Django 5.2.7 on 2025-11-28 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='work_end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='department',
            name='work_start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='department',
            name='working_days_per_week',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_offsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_wfh_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='attendance.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('preseent', 'Present'), ('half_day', 'Half Day'), ('on_leave', 'On leave'), ('unpaid_leave', 'Unpaid Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('late_minutes', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_auto_checkout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
